version: '3.4'

services:
  product-mgt-dashboard-be:
    container_name: product-mgt-dashboard-be
    image: ${DOCKER_REGISTRY-}productmgtdashboardbe
    build:
      context: .
      dockerfile: ProductMgtDashboardBe/Dockerfile
    ports:
      - 8001:8001
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8001
      - ASPNETCORE_URLS=http://+:8001
    volumes:
      - ./ProductMgtDashboardBe/sqlite3.db:/ProductMgtDashboardBe/sqlite3.db

  product-mgt-dashboard-fe:
    container_name: product-mgt-dashboard-fe
    build:
      context: .
      dockerfile: ProductMgtDashboardFe/Dockerfile
    ports:
      - 5173:5173
    environment:
      NODE_ENV: development