version: '3.4'

services:
  product-mgt-dashboard-db:
    container_name: product-mgt-dashboard-db
    image: keinos/sqlite3:3.50.1
    stdin_open: true
    tty: true
    volumes:
     - ./ProductMgtDashboardBe/sqlite3.db:/root/db/
  
  product-mgt-dashboard-be:
   image: ${DOCKER_REGISTRY-}productmgtdashboardbe
   build:
     context: .
     dockerfile: ProductMgtDashboardBe/Dockerfile
   ports:
      - 8001:8001
   links:
      - product-mgt-dashboard-db
   environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8001
      - ASPNETCORE_URLS=http://+:8001

  product-mgt-dashboard-fe:
    build: 
      context: .
      dockerfile: ProductMgtDashboardFe/Dockerfile
    ports:
      - "5173:5173"
    volumes:
     - ./ProductMgtDashboardFe:/app
     - ./ProductMgtDashboardFe/node_modules:/app/node_modules
    environment:
      NODE_ENV: development
    stdin_open: true
    tty: true
    command: npm run dev
